### ISSUE TITLE
Rewrite kmalloc and add a kvpalloc interface

### ISSUE THREAD

**Issue by JanzenJohn** [menix-os/menix#19]
### Menix Version

master

### Feature type

Change existing functionality

### Architecture

N/A

### Affected Area

Main

### Proposal

please add a function like kvpalloc (kernel virtual page alloc) which allows to allocate contiguous virtual pages, but does not guarantee physical pages to be contiguous. and maps that result to the requested virtual address

then implement kmalloc by running a slab allocator on pages acquired by kvpalloc

**Comment by marv7000** [comment]
Fixed with 13c1c7016f378a17e3acb2b39031c48bebb07a17 and b680d359b239d29b6bff141818f371e182226f07
